name: e2e

on:
  pull_request:
    branches: [V1]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/native-cli
    outputs:
      app: app/build/outputs/apk/release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle
      - run: touch .env && echo "PROJECT_ID=${{ secrets.CLOUD_PROJECT_ID }}" >> .env
      - run: npm install -g yarn
      - run: yarn
      - run: yarn android:build
      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: apps/native-cli/android/app/build/outputs/apk/release/app-release.apk
